version: 0.1

stages:
  - build

defaul-build:
  stage: 构建阶段
  job_type: image_build
  args:
  - server=true
  - bootstrap=true
  - advertise=120.25.244.184
  build_dir: /
  cache: true
  dockerfile_path: /Dockerfile
