version: "3.0"
stages:
- build
- deploy
job_build:
  stage: build
  job_type: image_build
  build_args: 
    - bootstrap-expect=3
  args:
    - disable-host-node-id=true
  build_dir: /
  cache: true
  dockerfile_path: /Dockerfile
job_deploy:
  stage: deploy
  job_type: DCS_deploy
  only:
    branches:
    - .*
    tags:
    - .*
  args:
    - disable-host-node-id=true
  app_name: green-music-consul-server