version: "3.0"
stages:
- build
- deploy
job_build:
  stage: build
  job_type: image_build
  build_args: 
    - bootstrap-expect=3
  build_dir: /
  cache: true
  dockerfile_path: /Dockerfile
job_deploy:
  stage: deploy
  job_type: DCS_deploy
  only:
    branches:
    - .*
    tags:
    - .*
  app_name: green-music-consul-server
  cluster_id: sr346813-8475-845a-a8j5-66e6z1d17a50
